In [1]:
import torch
torch.__version__

'2.3.1'

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX.ndim

2

In [12]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.4174, 0.4943, 0.1100, 0.5430],
         [0.7014, 0.8742, 0.0098, 0.3147],
         [0.3142, 0.5823, 0.0067, 0.1342]]),
 torch.float32)

In [16]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [17]:
ones = torch.ones(size=(3, 4))
ones, ones.size

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 <function Tensor.size>)

In [20]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype =None,
                               device = None,
                               requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [24]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float16)
float_16_tensor.dtype, float_16_tensor.device

(torch.float16, device(type='cpu'))

In [25]:
some_tensor = torch.rand(size=(3, 4))
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.9349, 0.7844, 0.5412, 0.2692],
        [0.5729, 0.9190, 0.6143, 0.2760],
        [0.1550, 0.0947, 0.2849, 0.1231]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulating Tensors

In [27]:
tensor = torch.tensor([1, 2, 3])
print(tensor)
print(tensor + 10)
print(tensor-10)
print(tensor * 10)

tensor([1, 2, 3])
tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])


In [28]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [29]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [30]:
print(tensor, "*", tensor)
print("Equals: ", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:  tensor([1, 4, 9])


## Matrix Multiplication

In [31]:
tensor

tensor([1, 2, 3])

In [32]:
# Element-wise multiplication
print(tensor*tensor)
# Matrix multiplication
print(torch.matmul(tensor, tensor))

tensor([1, 4, 9])
tensor(14)


In [33]:
tensor@tensor # "@" symbol for matrix multiplication

tensor(14)

In [34]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]
value

CPU times: user 422 μs, sys: 354 μs, total: 776 μs
Wall time: 597 μs


tensor(14)

In [36]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 65 μs, sys: 31 μs, total: 96 μs
Wall time: 59.1 μs


tensor(14)

In [37]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype =torch.float32)
tensor_B = torch.tensor([[7, 10],
                         [8 ,11],
                         [9, 12]], dtype=torch.float32)
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [38]:
print(tensor_B.T)

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [41]:
print(f"original shape: tensor_A={tensor_A.shape}, tensor_B={tensor_B.shape}")
print(f"new shapes: tensor_A = {tensor_A.shape} (sanme as above), tensor_B.T={tensor_B.T.shape}")
print(f"multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

original shape: tensor_A=torch.Size([3, 2]), tensor_B=torch.Size([3, 2])
new shapes: tensor_A = torch.Size([3, 2]) (sanme as above), tensor_B.T=torch.Size([2, 3])
multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [43]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [45]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2,
                         out_features=6)
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [47]:
weights = linear.weight
bias = linear.bias
weights, bias

(Parameter containing:
 tensor([[ 0.5406,  0.5869],
         [-0.1657,  0.6496],
         [-0.1549,  0.1427],
         [-0.3443,  0.4153],
         [ 0.6233, -0.5188],
         [ 0.6146,  0.1323]], requires_grad=True),
 Parameter containing:
 tensor([ 0.5224,  0.0958,  0.3410, -0.0998,  0.5451,  0.1045],
        requires_grad=True))

In [48]:
output_manual = torch.matmul(tensor_A, weights.T) + bias
output_manual

tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddBackward0>)

In [49]:
output_manual == output

tensor([[True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True]])

## Finding min, max, mean,sum, etc(aggregation)

In [51]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
print(f"Minimum: {x.min()}")
print(f"maxmum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Minimum: 0
maxmum: 90
Mean: 45.0
Sum: 450


In [53]:
torch.min(x), torch.max(x), torch.mean(x.type(torch.float32)),torch.sum(x)

(tensor(0), tensor(90), tensor(45.), tensor(450))

## Positional min, max

In [54]:
tensor = torch.arange(10, 100,10)
print(f"Tensor: {tensor}")

print(f"index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
index where max value occurs: 8
Index where min value occurs: 0


In [55]:
tensor =torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [56]:
tensor_float_16 = tensor.type(torch.float16)
tensor_float_16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

## reshaping, Stacking, Squeezing, and unsqueezing

In [57]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [58]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [59]:
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [61]:
y = torch.rand(size=(3, 8))
y, y.shape

(tensor([[0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539, 0.1952],
         [0.0050, 0.3068, 0.1165, 0.9103, 0.6440, 0.7071, 0.6581, 0.4913],
         [0.8913, 0.1447, 0.5315, 0.1587, 0.6542, 0.3278, 0.6532, 0.3958]]),
 torch.Size([3, 8]))

In [68]:
y_reshaped = torch.reshape(y, (6,4))
y_reshaped, y_reshaped.shape

(tensor([[0.7104, 0.9464, 0.7890, 0.2814],
         [0.7886, 0.5895, 0.7539, 0.1952],
         [0.0050, 0.3068, 0.1165, 0.9103],
         [0.6440, 0.7071, 0.6581, 0.4913],
         [0.8913, 0.1447, 0.5315, 0.1587],
         [0.6542, 0.3278, 0.6532, 0.3958]]),
 torch.Size([6, 4]))

In [69]:
z[:, 0]=5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [70]:
y_reshaped[:, 0]=0
y_reshaped

tensor([[0.0000, 0.9464, 0.7890, 0.2814],
        [0.0000, 0.5895, 0.7539, 0.1952],
        [0.0000, 0.3068, 0.1165, 0.9103],
        [0.0000, 0.7071, 0.6581, 0.4913],
        [0.0000, 0.1447, 0.5315, 0.1587],
        [0.0000, 0.3278, 0.6532, 0.3958]])

In [71]:
y_reshaped[:3, 0]=1
y_reshaped

tensor([[1.0000, 0.9464, 0.7890, 0.2814],
        [1.0000, 0.5895, 0.7539, 0.1952],
        [1.0000, 0.3068, 0.1165, 0.9103],
        [0.0000, 0.7071, 0.6581, 0.4913],
        [0.0000, 0.1447, 0.5315, 0.1587],
        [0.0000, 0.3278, 0.6532, 0.3958]])

In [73]:
y_reshaped[3:5, 0:3]=7
y_reshaped

tensor([[1.0000, 0.9464, 0.7890, 0.2814],
        [1.0000, 0.5895, 0.7539, 0.1952],
        [1.0000, 0.3068, 0.1165, 0.9103],
        [7.0000, 7.0000, 7.0000, 0.4913],
        [7.0000, 7.0000, 7.0000, 0.1587],
        [0.0000, 0.3278, 0.6532, 0.3958]])

In [74]:
x

tensor([5., 2., 3., 4., 5., 6., 7.])

In [75]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [78]:
print(f"Previous tensor: {x_stacked}")
print(f"Previous shape: {x_stacked.shape}")

x_stacked_squeezed = x_stacked.squeeze()
print(f"\nNew tensor: {x_stacked_squeezed}")
print(f"new shape: {x_stacked_squeezed.shape}")

Previous tensor: tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])
Previous shape: torch.Size([7, 4])

New tensor: tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])
new shape: torch.Size([7, 4])


In [76]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked


tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [77]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"new shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
new shape: torch.Size([7])


In [79]:
x = torch.zeros(2, 1, 2, 1, 2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [80]:
y = torch.squeeze(x)
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [81]:
x_original = torch.rand(size=(224, 224 , 3))
x_permuted = x_original.permute(2, 0, 1)
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [82]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [83]:
print(f"First square bracket:\n {x[0]}")
print(f"First square bracket:\n {x[0][0]}")
print(f"First square bracket:\n {x[0][0][0]}")

First square bracket:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
First square bracket:
 tensor([1, 2, 3])
First square bracket:
 1


In [84]:
x[:, 0]

tensor([[1, 2, 3]])

In [85]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [86]:
x[:, 1, 1]

tensor([5])

In [87]:
x[0, 0, :]

tensor([1, 2, 3])

In [88]:
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [89]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(f"random_tensor_A :{random_tensor_A}\n")
print(f"random_tensor_B :{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

random_tensor_A :tensor([[0.8973, 0.3629, 0.1748, 0.2401],
        [0.5457, 0.7303, 0.5268, 0.6694],
        [0.3213, 0.4008, 0.2892, 0.9977]])

random_tensor_B :tensor([[0.6649, 0.5646, 0.9323, 0.4621],
        [0.4027, 0.1680, 0.1170, 0.5063],
        [0.6061, 0.5141, 0.1907, 0.0445]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [90]:
import random

RANDOM_SEED = 42
torch.manual_seed(seed= RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C: \n {random_tensor_C}\n")
print(f"Tensor D: \n {random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C: 
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D: 
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running Tensors on GPUs

In [93]:
if torch.backends.mps.is_available():
    print("MPS backend is available.")
else:
    print("MPS backend is not available.")

MPS backend is available.


In [94]:
if torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device=torch.device("cpu")

In [95]:
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)
tensor_on_gpu = tensor.to(device) # type: ignore
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='mps:0')

In [98]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Exercises

In [100]:
Random_Tensor = torch.rand(size=(7,7))
Random_Tensor

tensor([[0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477],
        [0.6524, 0.6057, 0.3725, 0.7980, 0.8399, 0.1374, 0.2331],
        [0.9578, 0.3313, 0.3227, 0.0162, 0.2137, 0.6249, 0.4340],
        [0.1371, 0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816]])

In [101]:
Random_Tensor_0 = torch.rand(size=(1,7))
Random_Tensor_0

tensor([[0.9998, 0.5944, 0.6541, 0.0337, 0.1716, 0.3336, 0.5782]])

In [103]:
Multiplication = torch.matmul(Random_Tensor, Random_Tensor_0.T) # torch.mm, Random_Tensor @ Random_Tensor_0
Multiplication

tensor([[1.2748],
        [1.1652],
        [1.0182],
        [1.7959],
        [1.6076],
        [1.8623],
        [0.7118]])

In [110]:
torch.manual_seed(0)
Random_Tensor = torch.rand(size=(7,7))
Random_Tensor_0 = torch.rand(size=(1, 7))

Random_Tensor @ Random_Tensor_0.T

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [111]:
torch.manual_seed(0)
Random_Tensor = torch.rand(size=(7, 7))
Tensor_1 = Random_Tensor.to(device)
Random_Tensor_0 = torch.rand(size=(1, 7))
Tensor_2 = Random_Tensor_0.T.to(device)

Tensor_1 @ Tensor_2

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]], device='mps:0')

In [112]:
torch.manual_seed(1234)

device = "mps" if torch.backends.mps.is_available() else 'cpu'
print(f"Device: {device}")

tensor_A = torch.rand(size=(2, 3)).to(device)
tensor_B = torch.rand(size=(2, 3)).to(device)

tensor_A, tensor_B

Device: mps


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='mps:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='mps:0'))

In [113]:
tesnor_C = torch.matmul(tensor_A, tensor_B.T)
tesnor_C

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='mps:0')

In [114]:
max = torch.max(tesnor_C)
min = torch.min(tesnor_C)
max, min

(tensor(0.5617, device='mps:0'), tensor(0.3647, device='mps:0'))

In [115]:
arg_max = torch.argmax(tesnor_C)
arg_min = torch.argmin(tesnor_C)
arg_max, arg_min

(tensor(3, device='mps:0'), tensor(0, device='mps:0'))

In [118]:
Random = torch.rand(size=(1,1,1,10))
new_tensor =torch.squeeze(Random)
Random, new_tensor

(tensor([[[[0.7893, 0.3216, 0.5247, 0.6688, 0.8436, 0.4265, 0.9561, 0.0770,
            0.4108, 0.0014]]]]),
 tensor([0.7893, 0.3216, 0.5247, 0.6688, 0.8436, 0.4265, 0.9561, 0.0770, 0.4108,
         0.0014]))